name: Hello, World!
on: push

jobs:
  action-test:
    runs-on: ubuntu-latest
    name: Custom Action Text
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Verify hello action works
        uses: ./.github/actions/hello
